[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"

solc_version = "0.8.24"

optimizer = true
optimizer_runs = 200

evm_version = "cancun"

via_ir = false

bytecode_hash = "none"
cbor_metadata = false

ffi = false

gas_reports = ["*"]

fs_permissions = [
  { access = "read", path = "./" }
]

verbosity = 2

fuzz_runs = 256
